allow for socket activation

diff --git a/bin/em b/bin/em
--- a/bin/em
+++ b/bin/em
@@ -5,8 +5,13 @@ if [ "$(uname -s)" = "Darwin" ]; then
   . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh
 fi
 
-if ! command -v emacsclient >/dev/null 2>&1 || ! pgrep emacs >/dev/null 2>&1; then
+if ! command -v emacsclient >/dev/null 2>&1; then
   echo "No emacsclient, falling back to editor"
+  exec ~/.dotfiles/bin/editor "$@"
+fi
+
+if (! pgrep emacs >/dev/null 2>&1 && [ ! -S "$XDG_RUNTIME_DIR/emacs/server" ]); then
+  echo "emacs not running or systemd socket missing, falling back to editor"
   exec ~/.dotfiles/bin/editor "$@"
 fi
 
